apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

namePrefix: production-

commonLabels:
  variant: production
  app: tomcat-root-war

commonAnnotations:
  note: Hello, I am production!

patches:
- path: deployment.yaml
